-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Plain TEXT, not a Postgres ENUM, deliberately: ServiceNow can (and has)
-- introduced subscription-type labels not yet known to this codebase's own
-- domain.SubscriptionType vocabulary, and entity-service already tolerates
-- that on the ServiceNow side (see snTypeNameToSubscriptionType's own doc
-- comment: "never fails ... a type ServiceNow has added since
-- validSubscriptionTypes was last updated" still gets stored, just flagged
-- as unrecognized). An ENUM column would turn that same case into a hard
-- migration failure instead.
ALTER TABLE project ADD COLUMN IF NOT EXISTS subscription_type TEXT;
